name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Rust toolchain
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        components: rustfmt, clippy

    - name: Run linter
      run: cargo clippy --all-targets --all-features -- -D warnings
